name: Emscripten

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Checkout submodules
      shell: bash
      run: |
        git submodule sync
        git submodule update --init --force
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag libass/javascriptsubtitlesoctopus:latest
    - name: Build All
      run: docker run --rm -v ${PWD}:/code libass/javascriptsubtitlesoctopus:latest
    - uses: actions/upload-artifact@v1
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      with:
        name: js
        path: dist/js
